alias ls="eza"
alias ll="eza -laH --git"
alias gti="git"
alias gits="git status"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias diff="colordiff"
alias cat="bat -p"
alias grep="rg"
alias vim="nvim"
alias tf="terraform"
alias dc="docker-compose"
alias k="kubectl"
alias gc="gcloud"
alias sudo='sudo '
alias rm="rm -i"
alias mv="mv -i"

alias pdnsctl="dnsctl pdns"
alias pdns="dnsctl pdns"
