alias ls="eza"
alias ll="eza -laH --git"
alias gti="git"
alias gits="git status"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias diff="colordiff"
alias cat="bat -p"
alias grep="rg"
alias vim="nvim"
alias tf="terraform"
alias dc="docker-compose"
alias k="kubectl"
alias ks1="kubectl --context sys1.kube.demonware.net"
alias ki="kubectl --kubeconfig=/Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/kubeconfig-admin"
alias kk="kubectl --kubeconfig=/Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/e2e/kubeconfig"
alias fetchkk="/Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/fetch-cluster-creds.sh kind > /Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/e2e/kubeconfig"
alias fetchki="/Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/fetch-cluster-creds.sh managed> /Users/ikovalkovskyi/lohika/demonware/bonzai-system-tests/kubeconfig-admin"
alias gc="gcloud"
alias sudo='sudo '
alias rm="rm -i"
alias mv="mv -i"

alias goapplier="cd ~/lohika/demonware/kube-applier"
alias gobst="cd ~/lohika/demonware/bonzai-system-tests"
alias goktl="cd ~/lohika/demonware/kontroller"
alias godep="cd ~/lohika/demonware/kontroller-deploy"
alias gokauth="cd ~/lohika/demonware/kluster-authorization"
alias godemon="cd ~/lohika/demonware"
alias gocpo="cd ~/lohika/demonware/components-operator"

alias pdnsctl="dnsctl pdns"
alias pdns="dnsctl pdns"

alias ivanti="op item get \"Demonware Okta\" --format json | jq -r '.fields[] | select (.type == \"OTP\") | .totp' |  tr -d '\n' | pbcopy"
alias fixdns="sudo cp /etc/resolv.conf.bac /etc/resolv.conf;sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
